obj-m += simple_bof.o
 
all:
	make -C /tmp/linux-4.19.80 M=/home/bc/probs/my_kernel_challs/simple_bof/source modules
 
clean:
	make -C /tmp/linux-4.19.80 M=/home/bc/probs/my_kernel_challs/simple_bof/source clean
